Repository terra-money/fcd, pull requests merged in 2020-06, with the labels that each got.

#33 Fix/small fixes
  src/collector/dashboard/accountGrowth.ts
  src/collector/dashboard/blockReward.ts
  src/collector/dashboard/collectDashboard.ts
  src/collector/dashboard/helpers.ts
  src/collector/dashboard/rewardsInfo.ts
  src/collector/dashboard/stakingReturn.ts
  src/collector/dashboard/txVolume.ts
  src/service/dashboard/getActiveAccounts.ts
  src/stability/collectorSync.ts
  src/stability/constants.ts
  src/stability/fcdHealth.ts
  src/stability/nodeHealth.ts
  src/stability/stabilityChecker.ts
Labels: enhancement

#28 Fix/docs
  .gitignore
  README.md
  package.json
  src/controller/DashboardController.ts
  src/controller/GovernanceController.ts
  src/controller/MarketController.ts
  src/controller/StakingController.ts
  src/controller/TransactionController.ts
  src/controller/TreasuryController.ts
  src/createApp.ts
  yarn.lock
Labels: documentation

#37 Hotfix: not found error handling for lcd market/swap endpoint
  src/collector/block/block.ts
  src/collector/block/tx.ts
  src/collector/swap.ts
  src/createApp.ts
  src/e2etest/lcd.spec.ts
  src/lib/lcd.ts
  src/stability/collectorSync.ts
Labels: bug

#39 Fix/aws api gateway
  README.md
  src/controller/DashboardController.ts
  src/controller/TreasuryController.ts
  yarn.lock
Labels: documentation

#41 Fix/issue fcd 38 station 98
  src/collector/gov/collectProposal.ts
  src/collector/gov/removeProposal.ts
  src/collector/gov/saveProposal.ts
  src/controller/GovernanceController.ts
  src/controller/TransactionController.ts
  src/e2etest/tx.spec.ts
  src/service/transaction/parseMsg.ts
  src/service/transaction/parseTx.ts
  src/types/tx.d.ts
Labels: bug, enhancement

#40 Script/swagger merge tool
  README.md
  package.json
  src/controller/DashboardController.ts
  src/controller/GovernanceController.ts
  src/controller/MarketController.ts
  src/controller/StakingController.ts
  src/controller/TransactionController.ts
  src/scripts/mergeSwaggerFile.ts
  yarn.lock
Labels: enhancement

#50 BugFix and Improvement (issues 47-49)
  package.json
  sql/customIndex.sql
  src/collector/staking/validatorDetails.ts
  src/controller/TransactionController.ts
  src/createApp.ts
  src/orm/ValidatorInfoEntity.ts
  src/scripts/mergeSwaggerFile.ts
  src/scripts/testUrls.ts
  src/server.ts
  yarn.lock
Labels: bug, enhancement
